# Contract address of the layer 2 address to monitor
layer2-wallet-address: '0xdDbd8Ba27B66e57FD1D09b7CEe7Fb0470cac32Fd'
threshold: 1000000000000000000
# Amount of Ether you want to automatically bridge and send to the monitored address
amount: 20000000000000000
# How often should the Autotask run? (in minutes)
autotask-frequency: 60