service: bridge-automation
configValidationMode: error
frameworkVersion: "3"

provider:
  name: defender
  stage: dev
  stackName: bridge_automation
  ssot: false

# Configure and rename secret.secrets.yml to secrets.dev.yml
custom:
  secrets: ${file(../.secrets.${self:provider.stage}.yml)}
  config: ${file(./config.yml)}

# Make sure that you have created keys in your Defender account and added them to your secrets.dev.yml file
defender:
  key: ${self:custom.secrets.keys.defender-api-key}
  secret: ${self:custom.secrets.keys.defender-api-secret}

functions:
  autotask-1:
    name: Layer2 Contract Monitor Autotask
    path: autotask-1
    trigger:
      type: schedule
      # Set to check for new proposals every 60 minutes
      frequency: ${self:custom.config.autotask-frequency}
    paused: false
    relayer: ${self:resources.Resources.relayers.relayer-1}

resources:
  Resources:
    policies:
      policy-1:
        gas-price-cap: 1000
        whitelist-receivers:
          - ${self:custom.config.layer2-contract-address}
          - ${self:custom.config.layer2-relayer-address}
        eip1559-pricing: true

    secrets:
      stack:
        LAYER2_CONTRACT_ADDRESS: ${self:custom.config.layer2-contract-address}
        LAYER2_RELAYER_ADDRESS: ${self:custom.config.layer2-relayer-address}
        LAYER2_RELAYER_API_KEY: ${self:custom.secrets.layer2-relayer-address}
        LAYER2_RELAYER_API_SECRET: ${self:custom.secrets.layer2-relayer-address}
        LAYER1_RELAYER_API_KEY: ${self:custom.secrets.layer2-relayer-address}
        LAYER1_RELAYER_API_SECRET: ${self:custom.secrets.layer2-relayer-address}
        THRESHOLD: ${self:custom.config.threshold}

    relayers:
      relayer-1:
        name: Bridge Automation Relay Layer 1
        network: ${self:custom.config.relayer1-network}
        min-balance: 100000000000000000
      relayer-2:
        name: Bridge Automation Relay Layer 2
        network: ${self:custom.config.relayer2-network}
        min-balance: 100000000000000000

plugins:
  - defender-serverless