service: defender-serverless-template
configValidationMode: error
frameworkVersion: "3"

provider:
  name: defender
  stage: ${opt:stage, 'dev'}
  stackName: "${self:custom.config.network}-multisig" # prepend network name to separate between networks
  ssot: false

custom:
  secrets: ${file(../.secrets/${self:provider.stage}.yml)}
  config: ${file(./config.${self:provider.stage}.yml)}
  addresses: ${file(./config.${self:provider.stage}.yml)}

defender:
  key: ${self:custom.secrets.keys.defender-api-key}
  secret: ${self:custom.secrets.keys.defender-api-secret}

resources:
  Resources:
    sentinels:
      multisig-sentinel:
        name: "Multisig Monitor"
        type: "BLOCK"
        network: "${self:custom.config.network}"
        addresses:
          - "${self:custom.addresses.multisig-address}"
        abi: ${file(../../abi/Safe.json.abi)}
        paused: false
        autotask-condition: null
        autotask-trigger: null
        confirm-level: 1
        notify-config:
          channels:
            - ${self:resources.Resources.notifications.slack-security}
        conditions:
          event: # monitors all Safe events. If you don't want all of them just comment or remove
            - signature: "ChangedThreshold(uint256)"
            - signature: "AddedOwner(address)"
            - signature: "RemovedOwner(address)"
            - signature: "ApproveHash(bytes32,address)"
            - signature: "DisabledModule(address)"
            - signature: "EnabledModule(address)"
            - signature: "ExecutionFailure(bytes32,uint256)"
            - signature: "ExecutionFromModuleFailure(address)"
            - signature: "ExecutionFromModuleSuccess(address)"
            - signature: "ExecutionSuccess(bytes32,uint256)"
            - signature: "SignMsg(bytes32)"
            - signature: "ChangedFallbackHandler(address)"
            - signature: "ChangedGuard(address)"
            - signature: "SafeMultiSigTransaction(address,uint256,bytes,uint8,uint256,uint256,uint256,address,address,bytes,bytes)"
            - signature: "SafeReceived(address,uint256)"
            - signature: "SafeSetup(address,address[],uint256,address,address)"
            - signature: "SafeModuleTransaction(address,address,uint256,bytes,uint8)"
          function: # we don't monitor function calls in this sentinel
            - signature: ""

    notifications:
      slack-security:
        type: "slack"
        name: "Slack Security Channel"
        paused: false
        config:
          url: "${self:custom.secrets.notifications.slack-webhook}"

plugins:
  - defender-serverless
