service: defender-serverless-template
configValidationMode: error
frameworkVersion: "3"

provider:
  name: defender
  stage: ${opt:stage, 'dev'}
  stackName: "${self:custom.config.network}-multisig" #prepend network name to separate between networks
  ssot: false

custom:
  secrets: ${file(../secrets.${self:provider.stage}.yml)}
  config: ${file(../config.${self:provider.stage}.yml)}
  addresses: ${file(./addresses.${self:provider.stage}.yml)}

defender:
  key: ${self:custom.secrets.keys.api}
  secret: ${self:custom.secrets.keys.secret}

resources:
  Resources:
    sentinels:
      multisig-sentinel:
        name: "Multisig Monitor"
        type: "BLOCK"
        network: "${self:custom.config.network}"
        addresses:
          - "${self:custom.addresses.multisig-address}"
        abi: ${file(./abis/Safe.json.abi)}
        paused: false
        autotask-condition: null
        autotask-trigger: null
        confirm-level: 1
        notify-config:
          channels:
            - ${self:resources.Resources.notifications.slack-security}
        conditions:
          event:
            - signature: "ChangedThreshold(uint256)"
            - signature: "AddedOwner(address)"
            - signature: "RemovedOwner(address)"
          function: # we don't monitor function calls in this sentinel
            - signature: ""

    notifications:
      slack-security:
        type: "slack"
        name: "Slack Security Channel"
        paused: false
        config:
          url: "${self:custom.secrets.notifications.slack-webhook}"

plugins:
  - defender-serverless
