service: my-service
configValidationMode: error
frameworkVersion: '3'

provider:
  name: defender
  stage: ${opt:stage, 'dev'}
  stackName: 'poap-mint-tokens'
  ssot: false
custom:
  config: ${file(../.secrets/${self:provider.stage}.yml)}
defender:
  key: ${self:custom.config.keys.defender-api-key}
  secret: ${self:custom.config.keys.defender-api-secret}

functions:
  poap-autotask:
    name: 'Poap mint'
    path: './autotasks/mint-poap/dist'
    trigger:
      type: 'webhook'
    paused: true #Default paused you have to change this once autotask has correct addresses set
    relayer: ${self:resources.Resources.relayers.relayer-1}

resources:
  Resources:
    policies:
      policy-1:
        eip1559-pricing: true

    relayers:
      relayer-1:
        name: 'Poap minter Relayer'
        network: 'goerli'
        min-balance: 1000
        policy: ${self:resources.Resources.policies.policy-1}
plugins:
  - defender-serverless
