block_explorer_base_url: "https://etherscan.io/tx"
monitored-addresses:
    # Governance contract address
    - "0x7F5CA8e9664D66Fc7c11d26C7D9B750988d5c8a7"
# Possible Defender networks: https://github.com/OpenZeppelin/defender-client/blob/master/packages/base/src/utils/network.ts`
monitored-network: mainnet