block_explorer_base_url: 'https://etherscan.io/tx'
monitored-addresses:
  # Governance contract address
  - '0x7F5CA8e9664D66Fc7c11d26C7D9B750988d5c8a7'
  # The following address implements GovernorCompatibilityBravo
  # - "0xDBd38F7e739709fe5bFaE6cc8eF67C3820830E0C"
# Possible Defender networks: https://github.com/OpenZeppelin/defender-client/blob/master/packages/base/src/utils/network.ts`
monitored-network: mainnet
