service: governance-alert
configValidationMode: error
frameworkVersion: '3'

provider:
  name: defender
  stage: ${opt:stage, 'dev'}
  stackName: governance_alert
  ssot: false

# Configure and rename secret.example.yml to secrets.dev.yml
custom:
  config: ${file(./config.${self:provider.stage}.yml)}
  secrets: ${file(../.secrets/${self:provider.stage}.yml)}

# set up API keys in your Defender account and copy them to your ../.secrets/dev.yml file
defender:
  key: ${self:custom.secrets.keys.defender-api-key}
  secret: ${self:custom.secrets.keys.defender-api-secret}

functions:
  autotask-1:
    name: ${self:custom.config.name} Serverless Autotask
    path: autotask-1
    trigger:
      type: schedule
      frequency: 525600000
    paused: false

resources:
  Resources:
    policies:
      policy-1:
        gas-price-cap: 1000
        eip1559-pricing: true

    secrets:
      stack:
        block_explorer_base_url: ${self:custom.config.block_explorer_base_url}

    relayers:

    sentinels:
      sentinel-1:
        name: ${self:custom.config.name} Serverless Sentinel
        type: BLOCK
        addresses: ${self:custom.config.monitored-addresses}
        network: ${self:custom.config.monitored-network}
        abi: ${file(../../abi/contracts/GovernorMock.sol/GovernorMock.json.abi)}
        # To specifically target GovernorCompatibilityBravo events, which are a subset of Governor events,
        # comment out the previous line and uncomment the following line
        # abi: ${file(../../abi/contracts/GovernorCompatibilityBravoMock.sol/GovernorCompatibilityBravoMock.json.abi)}
        paused: false
        autotask-trigger: ${self:functions.autotask-1}
        confirm-level: 1
        notify-config:
          timeout: 0
          channels: []
        conditions:
          event:
            - signature: ProposalCanceled(uint256)
            - signature: >-
                ProposalCreated(uint256,address,address[],uint256[],string[],bytes[],uint256,uint256,string)
            - signature: ProposalExecuted(uint256)
            - signature: ProposalQueued(uint256,uint256)
            - signature: VoteCast(address,uint256,uint8,uint256,string)
            # The following events are emitted by Governor contract
            # - signature: ProposalThresholdSet(uint256, uint256)
            # - signature: QuorumNumeratorUpdated(uint256, uint256)
            # - signature: TimelockChange(address, address)
            # - signature: >-
            #    VoteCastWithParams(address, uint256, uint8, uint256, string, bytes)
            # - signature: VotingDelaySet(uint256, uint256)
            # - signature: VotingPeriodSet(uint256, uint256)
          function: []

plugins:
  - defender-serverless
