service: governance-automation
configValidationMode: error
frameworkVersion: "3"

provider:
  name: defender
  stage: dev
  stackName: governor_bravo_automation
  ssot: false

# Configure and rename secret.example.yml to secrets.dev.yml
custom:
  config: ${file(../secrets.dev.yml)}
  # Governor contract that the Autotask will automate
  governance-contract-address: "0xc0Da02939E1441F497fd74F78cE7Decb17B66529"

defender:
  key: ${self:custom.config.keys.api}
  secret: ${self:custom.config.keys.secret}

functions:
  autotask-1:
    name: Governor Bravo Automation Autotask
    path: autotask-1
    trigger:
      type: schedule
      # Set to check for new proposals every 5 minutes
      frequency: 60
    paused: false
    relayer: ${self:resources.Resources.relayers.relayer-1}

resources:
  Resources:
    policies:
      policy-1:
        gas-price-cap: 1000
        whitelist-receivers:
          - "0x0f06aB75c7DD497981b75CD82F6566e3a5CAd8f2"
        eip1559-pricing: true

    secrets:
      stack:
        GOVERNANCE_CONTRACT_ADDRESS: ${self:custom.governance-contract-address}

    relayers:
      relayer-1:
        name: Governor Bravo Automation Relay
        network: mainnet
        min-balance: 100000000000000000

plugins:
  - defender-serverless
